apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-simple-app-deployment
  labels:
    app: pb-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pb-simple-app
  template:
    metadata:
      labels:
        app: pb-simple-app
    spec:
      containers:
      - name: pb-simple-app-container
        image: aujung/pb-simple-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: pb-simple-app-service
spec:
  selector:
    app: pb-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
